version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0'
    steps:
      - checkout
      - run:
          name: Unit Test & Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=marna3_sample-springboot-cloudrun
      - run:
          name: Image Build
          command: mvn clean package docker:build

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
