version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Unit Test & Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=marna3_sample-springboot-cloudrun
      - run:
          name: Image Build
          command: mvn clean package docker:build 
            -DskipTests=True 
            -DgoogleCloudRegion=${GCP_REGION} 
            -DgoogleCloudProjectId=${GCP_PROJECT}

workflows:
  main:
    jobs:
      - build:
          name: Docker Build and Push
          context: 
          - SonarCloud
          - GoogleCloud
